pipeline:
  name: asdfsafsdf
  identifier: asdfsafsdf
  projectIdentifier: rajMigratorTest2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: asda
        identifier: asda
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: exit 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
