pipeline:
  name: test1 mar2
  identifier: test1_mar2
  projectIdentifier: TestAccResourceUserGroup_DeleteUnderlyingResource_TUeoH
  orgIdentifier: TestAccResourceUserGroup_DeleteUnderlyingResource_TUeoH
  tags: {}
  stages:
    - stage:
        name: S23
        identifier: S23
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
