---
- name: Update packages
  ansible.builtin.yum:
    name: "*"
    state: latest

- name: Install basic packages
  ansible.builtin.yum:
    name:
      - vim
      - curl
      - wget
      - htop
    state: present

- name: Set hostname
  ansible.builtin.hostname:
    name: "ansible-{{ inventory_hostname }}"
