# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    harness = {
      source = "harness/harness"
      version = "~> 0.14"
    }
  }
}

provider "harness" {
  endpoint          = "https://app.harness.io/gateway"
  account_id        = "UKh5Yts7THSMAbccG3HrLA"
  platform_api_key  = "pat.UKh5Yts7THSMAbccG3HrLA.67058d4de170274b1fba15c1.1DLsGEjMGHt0diXyPC5S"
}
