# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "raj-tg-infra-prod2-state"
    dynamodb_table = "tg-infra-prod2-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
