apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Change this port to match your application
  type: LoadBalancer # Use NodePort or ClusterIP if needed
