pipeline:
  stages:
    - name: Stage
      id: stage
      steps:
        - name: Step
          id: step
          run: echo "hello world"
        - name: rajTG
          id: rajtg
          iacm:
            uses: terragruntStep@1.0.3
            with:
              command: init
