pipeline:
  stages:
    - name: Stage
      id: stage
      workspace: <+inputs.workspace>
      steps:
        - name: rajTG
          id: rajtg
          iacm:
            uses: terragruntStep@1.0.3
            with:
              command: init
              connectorRef: account.rajdocker
              image: harnessdev/dev:270
  inputs:
    workspace:
      type: string
      description: IaCM workspace identifier
